name: Peer-Evident Impact B2B
favicon: null
layout_spectrum: 0.07082883268594742
typography_spectrum: 0.012393389130011201
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.41365686315111816
  lightness: 0.12214671331457794
  saturation: 0.4171166636515409
  rhythmicContrast: 0.6036815140396357
purpose: []
